platform :osx, '10.9'

xcodeproj "NewtonCommanderUI"

target "Demo" do
  pod "newton-commander-ui", :path => "../newton-commander-ui.podspec"
end

target "Tests" do
  pod "newton-commander-ui", :path => "../newton-commander-ui.podspec"
end

target "DemoMove" do
  pod "newton-commander-ui", :path => "../newton-commander-ui.podspec"
end

target "DemoCopy" do
  pod "newton-commander-ui", :path => "../newton-commander-ui.podspec"
end

